MODEL:
  # backbone part.
  BACKBONE:
    FREEZE_AT: 0
    NAME: "custom_bn_build_resnet_backbone" # we customize the momentum and eps in syncbn, to align with tf implementation.
  WEIGHTS: "../R-50.pkl"
  PIXEL_MEAN: [127.5, 127.5, 127.5]
  PIXEL_STD: [127.5, 127.5, 127.5]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["stem", "res2", "res3", "res4", "res5"]
    NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
  
  # kmax part.
  META_ARCHITECTURE: "kMaXDeepLab"
  SEM_SEG_HEAD:
    NAME: "kMaXDeepLabHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 8
    LOSS_WEIGHT: 1.0

  KMAX_DEEPLAB:
    SAVE_VIS_NUM: 0
    SHARE_FINAL_MATCHING: True
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 1e-5
    CLASS_WEIGHT: 3.0
    DICE_WEIGHT: 3.0
    MASK_WEIGHT: 0.3
    INSDIS_WEIGHT: 1.0
    AUX_SEMANTIC_WEIGHT: 0.0
    PIXEL_INSDIS_TEMPERATURE: 0.6
    PIXEL_INSDIS_SAMPLE_K: 4096

    PIXEL_DEC:
      NAME: "kMaXPixelDecoder"
      IN_FEATURES: ["stem", "res2", "res3", "res4", "res5"]
      DEC_LAYERS: [1, 5, 1, 1, 1]
      LAYER_TYPES: ["axial", "axial", "bottleneck", "bottleneck", "bottleneck"]
      DEC_CHANNELS: [512, 256, 128, 64, 32]

    TRANS_DEC:
      NAME: "kMaXTransformerDecoder"
      DEC_LAYERS: [2, 2, 2]
      NUM_OBJECT_QUERIES: 256
      IN_CHANNELS: [2048, 1024, 512, 128] # [512 * 4, 256 * 4, 128 * 4], the last dim is for final prediction
      DROP_PATH_PROB: 0.2

    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      PIXEL_CONFIDENCE_THRESHOLD: 0.4
      CLASS_THRESHOLD_THING: 0.5
      CLASS_THRESHOLD_STUFF: 0.3
      REORDER_CLASS_WEIGHT: 1.0
      REORDER_MASK_WEIGHT: 0.0
      OVERLAP_THRESHOLD: 0.9

DATASETS:
  TRAIN: ("cityscapes_fine_instance_seg_train",)
  TEST: ("cityscapes_fine_instance_seg_val",)
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.0003
  LR_SCHEDULER_NAME: "TF2WarmupPolyLR"
  MAX_ITER: 60000
  WARMUP_ITERS: 5000
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: False
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: [1025, 2049]
  MIN_SCALE: 0.5
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "cityscapes_instance_lsj"
  MIN_SIZE_TEST: 1025
  MAX_SIZE_TEST: 2049
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
VERSION: 2