MODEL:
  # backbone part.
  BACKBONE:
    FREEZE_AT: 0
    NAME: "custom_bn_build_resnet_backbone" # we customize the momentum and eps in syncbn, to align with tf implementation.
  WEIGHTS: "../R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
  
  # kmax part.
  META_ARCHITECTURE: "kMaXDeepLab"
  SEM_SEG_HEAD:
    NAME: "kMaXDeepLabHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 80
    LOSS_WEIGHT: 1.0

  KMAX_DEEPLAB:
    COPY_PASTE: False
    SAVE_VIS_NUM: 0
    SHARE_FINAL_MATCHING: True
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    DICE_WEIGHT: 5.0
    MASK_WEIGHT: 5.0
    INSDIS_WEIGHT: 0.0
    AUX_SEMANTIC_WEIGHT: 0.0

    PIXEL_DEC:
      NAME: "kMaXPixelDecoder"
      IN_FEATURES: ["res2", "res3", "res4", "res5"]
      DEC_LAYERS: [1, 5, 1, 1]
      LAYER_TYPES: ["axial", "axial", "bottleneck", "bottleneck"]
      DEC_CHANNELS: [512, 256, 128, 64]

    TRANS_DEC:
      NAME: "kMaXTransformerDecoder"
      DEC_LAYERS: [2, 2, 2]
      NUM_OBJECT_QUERIES: 128
      IN_CHANNELS: [2048, 1024, 512, 256] # [512 * 4, 256 * 4, 128 * 4], the last dim is for final prediction
      DROP_PATH_PROB: 0.2
      ITERATIVE_TRANS_DEC: False
      SIGMOID_KMEANS: False

    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      PIXEL_CONFIDENCE_THRESHOLD: 0.5
      CLASS_THRESHOLD_THING: 0.7
      CLASS_THRESHOLD_STUFF: 0.5
      REORDER_CLASS_WEIGHT: 1.0
      REORDER_MASK_WEIGHT: 1.0
      OVERLAP_THRESHOLD: 0.8

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 64
  BASE_LR: 0.0005
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  MAX_ITER: 150000
  WARMUP_ITERS: 5000
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: False
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: [1281, 1281]
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "coco_instance_lsj"
  MIN_SIZE_TEST: 1281
  MAX_SIZE_TEST: 1281
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
VERSION: 2