_BASE_: kmax_r50.yaml
MODEL:
  # backbone part.
  BACKBONE:
    NAME: "D2ConvNeXt"
  WEIGHTS: "../convnext_base_22k_1k_384.pkl"
  CONVNEXT:
    IN_CHANNELS: 3
    DEPTHS: [3, 3, 27, 3]
    DIMS: [128, 256, 512, 1024]
    # https://github.com/google-research/deeplab2/blob/main/configs/coco/kmax_deeplab/kmax_meta_convnext_base_os32.textproto#L28
    DROP_PATH_RATE: 0.5
    OUT_INDICES: [0, 1, 2, 3]